# IMPORTANT
# THIS SYNTAX WILL CREATE AN EMPTY DICTIONARY
a={}
print(type(a))

# An empty set can be created using the below syntax
b=set()
print(type(b))

# PROPERTIES OF SETS
'''
º) THERE IS NO WAY TO ALTER THE ELEMENTS OF A SET
º) WE CANNOT ACCESS ANY SET ELEMENT WITH INDEX VALUE(UNINDEXED)
º) SETS IGNORES DUPLICATE VALUES
º) SETS ARE UNORDERED
'''
